main: me.GhutenshtoffIndustries.GhutenshtoffToolkit.Main
name: GhutenshtoffToolkit
version: 1.2.1
author: Ghutenshtoff
description: Broadcasts messages
commands:
  bc:
    description: Broadcasts a message to all players in chat
    usage: /bc <message>
    permission: ghutenshtofftooklit.broadcast
  heal:
    description: Heals the command executor
    usage: /heal
    permission: ghutenshtofftooklit.heal
  feed:
    description: Feeds the command executor
    usage: /feed
    permission: ghutenshtofftooklit.feed
  fly:
    description: Allows the command executor to fly
    usage: /fly
    permission: ghutenshtofftooklit.fly